name: E2E Tests Pipeline

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browser Chrome
      run: npx playwright install --with-deps chromium

    - name: Run tests
      run: npm test

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber_report.html
        path: cucumber_report.html